/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tasks;

import java.awt.Color;

/**
 *
 * @author yurin
 */
public class FloatText extends javax.swing.JDialog {

    /**
     * Creates new form FloatText
     */
    public FloatText(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setBackground(new Color(0,0,0,0));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        textArea = new javax.swing.JTextArea();
        exitBT = new javax.swing.JButton();
        resizeBT = new javax.swing.JButton();
        moveBT = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setBackground(new java.awt.Color(22, 22, 22));
        setUndecorated(true);
        getContentPane().setLayout(new java.awt.GridBagLayout());

        textArea.setColumns(20);
        textArea.setRows(5);
        jScrollPane1.setViewportView(textArea);

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipadx = 380;
        gridBagConstraints.ipady = 280;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(jScrollPane1, gridBagConstraints);

        exitBT.setBackground(new java.awt.Color(22, 22, 22));
        exitBT.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        exitBT.setForeground(new java.awt.Color(153, 0, 0));
        exitBT.setText("X");
        exitBT.setBorder(null);
        exitBT.setFocusPainted(false);
        exitBT.setMaximumSize(new java.awt.Dimension(20, 16));
        exitBT.setMinimumSize(new java.awt.Dimension(20, 16));
        exitBT.setPreferredSize(new java.awt.Dimension(20, 16));
        exitBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitBTMouseClicked(evt);
            }
        });
        exitBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        getContentPane().add(exitBT, gridBagConstraints);

        resizeBT.setBackground(new java.awt.Color(22, 22, 22));
        resizeBT.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        resizeBT.setForeground(new java.awt.Color(51, 204, 0));
        resizeBT.setText("╝");
        resizeBT.setBorder(null);
        resizeBT.setFocusPainted(false);
        resizeBT.setMaximumSize(new java.awt.Dimension(20, 16));
        resizeBT.setMinimumSize(new java.awt.Dimension(20, 16));
        resizeBT.setPreferredSize(new java.awt.Dimension(20, 16));
        resizeBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                resizeBTMouseClicked(evt);
            }
        });
        resizeBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resizeBTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LAST_LINE_START;
        getContentPane().add(resizeBT, gridBagConstraints);

        moveBT.setBackground(new java.awt.Color(22, 22, 22));
        moveBT.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        moveBT.setForeground(new java.awt.Color(51, 204, 0));
        moveBT.setText("[ ]");
        moveBT.setBorder(null);
        moveBT.setFocusPainted(false);
        moveBT.setMaximumSize(new java.awt.Dimension(20, 16));
        moveBT.setMinimumSize(new java.awt.Dimension(20, 16));
        moveBT.setPreferredSize(new java.awt.Dimension(20, 16));
        moveBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                moveBTMouseClicked(evt);
            }
        });
        moveBT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                moveBTActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.FIRST_LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(17, 0, 0, 0);
        getContentPane().add(moveBT, gridBagConstraints);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitBTMouseClicked
        
    }//GEN-LAST:event_exitBTMouseClicked

    private void exitBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitBTActionPerformed

    private void resizeBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_resizeBTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_resizeBTMouseClicked

    private void resizeBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resizeBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_resizeBTActionPerformed

    private void moveBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_moveBTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_moveBTMouseClicked

    private void moveBTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_moveBTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_moveBTActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
       
        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FloatText dialog = new FloatText(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exitBT;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton moveBT;
    private javax.swing.JButton resizeBT;
    private javax.swing.JTextArea textArea;
    // End of variables declaration//GEN-END:variables
}
