/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tasks;

import java.awt.Color;
import java.awt.event.KeyEvent;

/**
 *
 * @author yurin
 */
public class Task extends javax.swing.JPanel {

    /**
     * Creates new form TaskItemPanel
     */
    private final Main main;

    public Task(Main frame) {
        this.main = frame;
        initComponents();
        init();
    }

    public void setButtonsVisible() {
        removeBT.setVisible(true);
        doneBT.setVisible(true);
    }

    public void setButtonsInvisible() {
        removeBT.setVisible(false);
        doneBT.setVisible(false);
    }

    private void init() {
        titleEditField.setVisible(false);
        titleEditField.setSelectionColor(Color.green);
        setBackground(new Color(0, 0, 0, 255));
        setButtonsInvisible();
    }

    private void saveText() {
        this.setVisible(false);
        titleEditField.setVisible(false);
        titleLabel.setText(titleEditField.getText());
        titleLabel.setVisible(true);
        this.setVisible(true);
        main.refreshView();
        main.refreshView();
    }

    private void editText() {
        this.setVisible(false);
        titleLabel.setVisible(false);
        titleEditField.setText(titleLabel.getText());
        titleEditField.setVisible(true);
        this.setVisible(true);
        titleEditField.selectAll();
        titleEditField.requestFocus();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        removeBT = new javax.swing.JButton();
        doneBT = new javax.swing.JButton();
        titleLabel = new javax.swing.JLabel();
        titleEditField = new javax.swing.JTextField();

        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                formMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                formMouseExited(evt);
            }
        });
        setLayout(new java.awt.GridBagLayout());

        removeBT.setBackground(new java.awt.Color(22, 22, 22));
        removeBT.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        removeBT.setForeground(new java.awt.Color(145, 0, 51));
        removeBT.setText("X");
        removeBT.setBorder(null);
        removeBT.setFocusPainted(false);
        removeBT.setPreferredSize(new java.awt.Dimension(19, 16));
        removeBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removeBTMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 2);
        add(removeBT, gridBagConstraints);

        doneBT.setBackground(new java.awt.Color(22, 22, 22));
        doneBT.setFont(new java.awt.Font("Courier New", 1, 13)); // NOI18N
        doneBT.setForeground(new java.awt.Color(102, 153, 0));
        doneBT.setText("ѵ");
        doneBT.setBorder(null);
        doneBT.setFocusPainted(false);
        doneBT.setPreferredSize(new java.awt.Dimension(19, 16));
        doneBT.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                doneBTMouseClicked(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        add(doneBT, gridBagConstraints);

        titleLabel.setForeground(new java.awt.Color(51, 204, 0));
        titleLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        titleLabel.setText("task title");
        titleLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                titleLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                titleLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                titleLabelMouseExited(evt);
            }
        });
        titleLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleLabelKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(titleLabel, gridBagConstraints);

        titleEditField.setBackground(new java.awt.Color(22, 22, 22));
        titleEditField.setForeground(new java.awt.Color(0, 255, 0));
        titleEditField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        titleEditField.setText("task title");
        titleEditField.setToolTipText("");
        titleEditField.setAlignmentX(0.0F);
        titleEditField.setBorder(null);
        titleEditField.setMaximumSize(new java.awt.Dimension(49, 16));
        titleEditField.setMinimumSize(new java.awt.Dimension(49, 16));
        titleEditField.setName(""); // NOI18N
        titleEditField.setOpaque(false);
        titleEditField.setPreferredSize(new java.awt.Dimension(49, 16));
        titleEditField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                titleEditFieldFocusLost(evt);
            }
        });
        titleEditField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                titleEditFieldKeyPressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridheight = java.awt.GridBagConstraints.RELATIVE;
        gridBagConstraints.fill = java.awt.GridBagConstraints.BOTH;
        gridBagConstraints.ipady = 25;
        gridBagConstraints.insets = new java.awt.Insets(0, 3, 0, 0);
        add(titleEditField, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void titleLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseClicked
        editText();
    }//GEN-LAST:event_titleLabelMouseClicked

    private void titleLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleLabelKeyPressed

    }//GEN-LAST:event_titleLabelKeyPressed


    private void titleEditFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_titleEditFieldKeyPressed
        if (KeyEvent.VK_ENTER == evt.getKeyCode()) {
            saveText();
        }
    }//GEN-LAST:event_titleEditFieldKeyPressed

    private void titleEditFieldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_titleEditFieldFocusLost
        saveText();
    }//GEN-LAST:event_titleEditFieldFocusLost

    private void removeBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removeBTMouseClicked
        main.deleteTask(this);
    }//GEN-LAST:event_removeBTMouseClicked

    private void doneBTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_doneBTMouseClicked
        this.remove(doneBT);
        setBackground(new Color(0, 25, 0, 100));
        main.refreshView();
    }//GEN-LAST:event_doneBTMouseClicked

    private void titleLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseEntered

    }//GEN-LAST:event_titleLabelMouseEntered

    private void titleLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_titleLabelMouseExited

    }//GEN-LAST:event_titleLabelMouseExited

    private void formMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseEntered


    }//GEN-LAST:event_formMouseEntered

    private void formMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseExited

    }//GEN-LAST:event_formMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton doneBT;
    private javax.swing.JButton removeBT;
    private javax.swing.JTextField titleEditField;
    private javax.swing.JLabel titleLabel;
    // End of variables declaration//GEN-END:variables

}
